exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

line-length = 320
indent-width = 4

# Must not exceed requires-python in pyproject.toml
target-version = "py311"

[lint]
preview = true

select = ["ALL"]
ignore = [ "f-string-in-exception", "too-many-public-methods", "magic-value-comparison", "raise-vanilla-args", "doc-line-too-long", "bad-quotes-inline-string", "avoidable-escaped-quote", "missing-trailing-comma"]
extend-select = ["DOC"]

fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
preview = true

quote-style = "double"
docstring-code-format = true

indent-style = "space"

line-ending = "auto"

[lint.per-file-ignores]
"__init__.py" = ["unused-import"]
"docs/conf.py" = ["implicit-namespace-package"]
"**/{tests,docs,tools}/*" = ["undocumented-public-method", "missing-return-type-undocumented-public-function", "pytest-unittest-assertion", "call-datetime-without-tzinfo", "pytest-unittest-raises-assertion", "undocumented-public-class", "undocumented-public-module", "missing-copyright-notice", "unnecessary-literal-within-tuple-call", "unnecessary-literal-set", "unnecessary-literal-within-tuple-call", "blind-except", "suspicious-non-cryptographic-random-usage", "suspicious-pickle-usage", "suspicious-pickle-import", "undocumented-public-package"]

[lint.flake8-quotes]
inline-quotes = "single"

[lint.pydocstyle]
convention = "google"

[lint.pycodestyle]
max-doc-length = 320
