name: Publish
on:
  release:
    types: [published]
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements_dev.txt
            - name: Build package
              run: |
                python -m pip install --upgrade build
                python -m build --sdist --wheel
            - name: Publish package to PyPI
              uses: pypa/gh-action-pypi-publish@v1.5.1
              with:
                user: __token__
                password: ${{ secrets.PYPI_API_TOKEN }}
