name: vulture

on:
  push:
    branches: [ "main", "homolog" ]
  pull_request:
    branches: [ "main", "homolog" ]

jobs:
    vulture:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Run Vulture
          uses: gtkacz/vulture-action@v1
          with:
            args: '. --min-confidence 70 --exclude "tests,docs" --verbose'
